version: "3.9"

services:
  # frontend:
  #   build:
  #     context: ./Velochat.Frontend
  #     dockerfile: Dockerfile
  #   restart: always
  #   ports:
  #     - "5173:5173"
  #   depends_on:
  #     - backend
  #   environment:
  #     BACKEND_URL: "http://localhost:5000"
  
  backend:
    build:
      context: ./Velochat.Backend
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    depends_on:
      - db
    environment:
      Db__ConnectionString: "Host=db;Port=5432;Database=velochat;Username=velochat;Password=velochat"
      ASPNETCORE_URLS: "http://localhost:8080"
      Jwt__Secret: "6SecretSecretSecretSecretSecretSecret"
      DOTNET_ENVIRONMENT: "Development"

  db:
    build:
      context: ./Velochat.Database
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./Velochat.Database/initdb:/docker-entrypoint-initdb.d

    environment:
      POSTGRES_USER: velochat
      POSTGRES_PASSWORD: velochat
      POSTGRES_DB: velochat

  # db__cron:
  #   build:
  #     context: ./Velochat.Database.Cron
  #     dockerfile: Dockerfile
  #   restart: always
  #   depends_on:
  #     - db

volumes:
  pgdata: